/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas.Gui.Formularios.Alumno;

import Dominio.Alumno;
import Dto.AlumnoDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lm-carlos
 */
public class AlumnoTodosFormulario extends javax.swing.JDialog {

    /**
     * Creates new form AlumnoTodosFormulario
     */
    public AlumnoTodosFormulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        tablaAlumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        // Ajustar el tamaño de columnas para que quepan mejor si quieres
        tablaAlumnos.setPreferredScrollableViewportSize(tablaAlumnos.getPreferredSize());

        tablaAlumnos.getColumnModel().getColumn(0).setPreferredWidth(50);   // ID
        tablaAlumnos.getColumnModel().getColumn(1).setPreferredWidth(150);  // Nombres
        tablaAlumnos.getColumnModel().getColumn(2).setPreferredWidth(150);  // Apellidos
        tablaAlumnos.getColumnModel().getColumn(3).setPreferredWidth(120);  // Contraseña
        tablaAlumnos.getColumnModel().getColumn(4).setPreferredWidth(200);  // Email
        tablaAlumnos.getColumnModel().getColumn(5).setPreferredWidth(120);  // Teléfono
        tablaAlumnos.getColumnModel().getColumn(6).setPreferredWidth(200);  // Dirección
        tablaAlumnos.getColumnModel().getColumn(7).setPreferredWidth(150);  // Fecha de Nacimiento
        tablaAlumnos.getColumnModel().getColumn(8).setPreferredWidth(150);  // Nombre del Acudiente
        tablaAlumnos.getColumnModel().getColumn(9).setPreferredWidth(150);  // Apellido del Acudiente
        tablaAlumnos.getColumnModel().getColumn(10).setPreferredWidth(100); // Parentesco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                cargarTablaAlumnos(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(2000, 372));

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Contraseña", "Email", "Teléfono", "Dirección", "Fecha de Nacimiento", "Nombre del Acudiente", "Apellido del Acudiente", "Parentesco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAlumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tablaAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTablaAlumnos(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cargarTablaAlumnos
        // TODO add your handling code here:
        System.out.println("XXXXXXXXXXXXXXXXXXXXXx");
        try {
            List<Alumno> lista = AlumnoDto.listarTodo();  // Obtener lista de alumnos

            DefaultTableModel modelo = (DefaultTableModel) tablaAlumnos.getModel();
            modelo.setRowCount(0); // Limpiar la tabla antes de llenar

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay elementos que mostrar");
            }

            for (Alumno a : lista) {
                System.out.println("Agregando: " + a.getNombres() + " " + a.getApellidos());
                Object[] fila = {
                    a.getId(),
                    a.getNombres(),
                    a.getApellidos(),
                    a.getContrasena(),
                    a.getEmail(),
                    a.getTelefono(),
                    a.getDireccion(),
                    a.getFechaNacimiento(),
                    a.getNombreAcudiente(),
                    a.getApellidoAcudiente(),
                    a.getParentesco()
                // Puedes agregar más campos si tienes más columnas
                };
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar alumnos: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_cargarTablaAlumnos

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoTodosFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoTodosFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoTodosFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoTodosFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlumnoTodosFormulario dialog = new AlumnoTodosFormulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlumnos;
    // End of variables declaration//GEN-END:variables
}
