/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas.Gui.Formularios.NivelEducativo;

import Dominio.NivelEducativo;
import Dominio.Constantes.TipoNivelEducativo;
import Dto.NivelEducativoDto;
import java.awt.Frame;
import javax.swing.JOptionPane;
import org.jdatepicker.impl.JDatePickerImpl;

/**
 *
 * @author lm-carlos
 */
public class NivelEducativoFormulario extends javax.swing.JDialog {

    /**
     * Creates new form NivelEducativoFormulario
     */
    private JDatePickerImpl datePicker;

    public NivelEducativoFormulario(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAgregar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        selectorTipo = new javax.swing.JComboBox<>();
        campoNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        etiquetaError = new javax.swing.JLabel();
        botonListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonAgregar.setText("Agregar");
        botonAgregar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar(evt);
            }
        });

        botonLimpiar.setText("Limpiar");
        botonLimpiar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Formulario Nivel Educativo");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripción");

        jLabel10.setText("Tipo");

        selectorTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "INFANTIL", "PRIMARIA", "SECUNDARIA", "BACHILLERATO" }));
        selectorTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTipoActionPerformed(evt);
            }
        });

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        jLabel12.setText("Código");

        campoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdActionPerformed(evt);
            }
        });

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        etiquetaError.setForeground(new java.awt.Color(255, 0, 51));
        etiquetaError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botonListar.setText("Listar");
        botonListar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addGap(23, 23, 23)
                        .addComponent(botonListar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiquetaError, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(etiquetaError, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonListar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEditar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectorTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorTipoActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdActionPerformed

    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        // TODO add your handling code here:
        etiquetaError.setText("");

        try {
            NivelEducativoDto nivelEducativoDto = new NivelEducativoDto();
            String campoIdTexto = campoId.getText();
            Long id = Long.parseLong(campoIdTexto);

            NivelEducativo nivelEducativoBuscado = nivelEducativoDto.buscar(id);

            // Validación básica
            if (nivelEducativoBuscado == null || nivelEducativoBuscado.getId() == null) {
                String message = "No se encontró ningun Nivel Educativo con ese ID.";
                etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
                return;
            }

            // Llenar campos
            campoNombre.setText(nivelEducativoBuscado.getNombre());
            campoDescripcion.setText(nivelEducativoBuscado.getDescripcion());
            selectorTipo.setSelectedItem(nivelEducativoBuscado.getTipo().toString());

        } catch (NumberFormatException ex) {
            String message = "El ID debe ser un número válido.";
            etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
        } catch (Exception e) {
            String message = "Ocurrió un error al buscar el Nivel Educativo.";
            etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
            e.printStackTrace();
        }

    }//GEN-LAST:event_buscar

    private void agregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar
        // TODO add your handling code here:

        etiquetaError.setText("");

        try {
            NivelEducativo nuevoNivelEducativo = new NivelEducativo();

            nuevoNivelEducativo.setNombre(campoNombre.getText());
            nuevoNivelEducativo.setDescripcion(campoDescripcion.getText());
            
            String tipoSeleccionado = (String) selectorTipo.getSelectedItem();
            nuevoNivelEducativo.setTipo(TipoNivelEducativo.valueOf(tipoSeleccionado));

            NivelEducativoDto.guardar(nuevoNivelEducativo);

            JOptionPane.showMessageDialog(this, "Nivel Educativo agregado con éxito.");

        } catch (Exception e) {
            etiquetaError.setText("<html><body style='width: 180px;'>" + e.getMessage() + "</body></html>");

            e.printStackTrace();
        }
    }//GEN-LAST:event_agregar

    private void editar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar
        // TODO add your handling code here:
        etiquetaError.setText("");

        try {
            NivelEducativoDto nivelEducativoDto = new NivelEducativoDto();
            String campoIdTexto = campoId.getText();
            Long id = Long.parseLong(campoIdTexto);

            NivelEducativo nivelEducativoBuscado = nivelEducativoDto.buscar(id);

            // Validación básica
            if (nivelEducativoBuscado == null || nivelEducativoBuscado.getId() == null) {
                String message = "No se encontró ninguna nivelEducativo con ese ID.";
                etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
                return;
            }

            // Actualizar valores
            nivelEducativoBuscado.setNombre(campoNombre.getText());
            nivelEducativoBuscado.setDescripcion(campoDescripcion.getText());

            String tipoSeleccionado = (String) selectorTipo.getSelectedItem();
            nivelEducativoBuscado.setTipo(TipoNivelEducativo.valueOf(tipoSeleccionado));
            
            NivelEducativoDto.editar(nivelEducativoBuscado);

            JOptionPane.showMessageDialog(this, "Nivel Educativo editado con éxito.");

        } catch (NumberFormatException ex) {
            String message = "El ID debe ser un número válido.";
            etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
        } catch (Exception e) {
            String message = "Ocurrió un error al buscar el Nivel Educativo.";
            etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
            e.printStackTrace();
        }


    }//GEN-LAST:event_editar

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        // TODO add your handling code here:
        etiquetaError.setText("");

        campoId.setText("");
            campoNombre.setText("");
            campoDescripcion.setText("");
            selectorTipo.setSelectedItem(" ");
    }//GEN-LAST:event_limpiar

    private void eliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar
        // TODO add your handling code here:
        etiquetaError.setText("");

        try {
            NivelEducativoDto nivelEducativoDto = new NivelEducativoDto();
            String campoIdTexto = campoId.getText();
            Long id = Long.parseLong(campoIdTexto);

            NivelEducativo nivelEducativoBuscado = nivelEducativoDto.buscar(id);

            // Validación básica
            if (nivelEducativoBuscado == null || nivelEducativoBuscado.getId() == null) {
                String message = "No se encontró ningun Nivel Educativo con ese ID.";
                etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
                return;
            }

            // Eliminar
            
            NivelEducativoDto.eliminar(id);

            JOptionPane.showMessageDialog(this, "Nivel Educativo eliminado con éxito.");

        } catch (NumberFormatException ex) {
            String message = "El ID debe ser un número válido.";
            etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
        } catch (Exception e) {
            String message = "Ocurrió un error al eliminar el Nivel Educativo.";
            etiquetaError.setText("<html><body style='width: 180px;'>" + message + "</body></html>");
            e.printStackTrace();
        }

        
    }//GEN-LAST:event_eliminar

    private void botonListar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListar
        // TODO add your handling code here:
        Frame frame = JOptionPane.getFrameForComponent(this);
        NivelEducativoTodosFormulario ventana = new NivelEducativoTodosFormulario(frame, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_botonListar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelEducativoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelEducativoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelEducativoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelEducativoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NivelEducativoFormulario dialog = new NivelEducativoFormulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonListar;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel etiquetaError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectorTipo;
    // End of variables declaration//GEN-END:variables
}
