/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Gui;

import Dominio.CicloAcademico;
import Dominio.NivelEducativo;
import Vistas.Gui.Formularios.Administrativo.AdministrativoFormulario;
import Vistas.Gui.Formularios.Alumno.AlumnoFormulario;
import Vistas.Gui.Formularios.Asignatura.AsignaturaFormulario;
import Vistas.Gui.Formularios.Aula.AulaFormulario;
import Vistas.Gui.Formularios.CicloAcademico.CicloAcademicoFormulario;
import Vistas.Gui.Formularios.Curso.CursoFormulario;
import Vistas.Gui.Formularios.Modalidad.ModalidadFormulario;
import Vistas.Gui.Formularios.NivelEducativo.NivelEducativoFormulario;
import Vistas.Gui.Formularios.ProfesorInfantil.ProfesorInfantilFormulario;
import Vistas.Gui.Formularios.ProfesorRegular.ProfesorRegularFormulario;
import Vistas.Gui.UsuariosGui.VentanaLogin;

/**
 *
 * @author lm-carlos
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        categoriaUsuario = new javax.swing.JMenu();
        menuAlumno = new javax.swing.JMenu();
        itemAgregarAlumno = new javax.swing.JMenuItem();
        itemBuscarAlumno = new javax.swing.JMenuItem();
        itemEditarAlumno = new javax.swing.JMenuItem();
        itemEliminarAlumno = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesAlumno = new javax.swing.JMenu();
        itemBuscarPorNombreAlumno = new javax.swing.JMenuItem();
        itemBuscarPorIdAlumno = new javax.swing.JMenuItem();
        menuAdministrativo = new javax.swing.JMenu();
        itemAgregarAdministrativo = new javax.swing.JMenuItem();
        itemBuscarAdministrativo = new javax.swing.JMenuItem();
        itemEditarAdministrativo = new javax.swing.JMenuItem();
        itemEliminarAdministrativo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesAdministrativo = new javax.swing.JMenu();
        itemBuscarPorNombreAdministrativo = new javax.swing.JMenuItem();
        itemBuscarPorIdAdministrativo = new javax.swing.JMenuItem();
        menuProfesorRegular = new javax.swing.JMenu();
        itemAgregarProfesorRegular = new javax.swing.JMenuItem();
        itemBuscarProfesorRegular = new javax.swing.JMenuItem();
        itemEditarProfesorRegular = new javax.swing.JMenuItem();
        itemEliminarProfesorRegular = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesProfesorRegular = new javax.swing.JMenu();
        itemBuscarPorNombreProfesorRegular = new javax.swing.JMenuItem();
        itemBuscarPorIdProfesorRegular = new javax.swing.JMenuItem();
        menuProfesorInfantil = new javax.swing.JMenu();
        itemAgregarProfesorInfantil = new javax.swing.JMenuItem();
        itemBuscarProfesorInfantil = new javax.swing.JMenuItem();
        itemEditarProfesorInfantil = new javax.swing.JMenuItem();
        itemEliminarProfesorInfantil = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesProfesorInfantil = new javax.swing.JMenu();
        itemBuscarPorNombreProfesorInfantil = new javax.swing.JMenuItem();
        itemBuscarPorIdProfesorInfantil = new javax.swing.JMenuItem();
        itemLoginUsuario = new javax.swing.JMenuItem();
        itemRecordarClaveUsuario = new javax.swing.JMenuItem();
        itemCambiarClaveUsuario = new javax.swing.JMenuItem();
        itemSalirUsuario = new javax.swing.JMenuItem();
        categoriaVinculacion = new javax.swing.JMenu();
        menuMatricula = new javax.swing.JMenu();
        itemAgregarMatricula = new javax.swing.JMenuItem();
        itemBuscarMatricula = new javax.swing.JMenuItem();
        itemEditarMatricula = new javax.swing.JMenuItem();
        itemEliminarMatricula = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesMatricula = new javax.swing.JMenu();
        itemBuscarPorEstudianteMatricula = new javax.swing.JMenuItem();
        itemBuscarPorIdMatricula = new javax.swing.JMenuItem();
        menuBeca = new javax.swing.JMenu();
        itemAgregarBeca = new javax.swing.JMenuItem();
        itemBuscarBeca = new javax.swing.JMenuItem();
        itemEditarBeca = new javax.swing.JMenuItem();
        itemEliminarBeca = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesBeca = new javax.swing.JMenu();
        itemBuscarPorNombreBeca = new javax.swing.JMenuItem();
        itemBuscarPorIdBeca = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuContrato = new javax.swing.JMenu();
        itemAgregarContrato = new javax.swing.JMenuItem();
        itemBuscarContrato = new javax.swing.JMenuItem();
        itemEditarContrato = new javax.swing.JMenuItem();
        itemEliminarContrato = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesContrato = new javax.swing.JMenu();
        itemBuscarPorNombreContrato = new javax.swing.JMenuItem();
        itemBuscarPorIdContrato = new javax.swing.JMenuItem();
        categoriaAdministracion = new javax.swing.JMenu();
        menuCicloAcademico = new javax.swing.JMenu();
        itemAgregarCicloAcademico = new javax.swing.JMenuItem();
        itemBuscarCicloAcademico = new javax.swing.JMenuItem();
        itemEditarCicloAcademico = new javax.swing.JMenuItem();
        itemEliminarCicloAcademico = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesCicloAcademico = new javax.swing.JMenu();
        itemBuscarPorAnioCicloAcademico = new javax.swing.JMenuItem();
        itemBuscarPorIdCicloAcademico = new javax.swing.JMenuItem();
        menuServicioComplementario = new javax.swing.JMenu();
        itemAgregarServicioComplementario = new javax.swing.JMenuItem();
        itemBuscarServicioComplementario = new javax.swing.JMenuItem();
        itemEditarServicioComplementario = new javax.swing.JMenuItem();
        itemEliminarServicioComplementario = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesServicioComplementario = new javax.swing.JMenu();
        itemBuscarPorNombreServicioComplementario = new javax.swing.JMenuItem();
        itemBuscarPorIdServicioComplementario = new javax.swing.JMenuItem();
        categoriaOrganizacion = new javax.swing.JMenu();
        menuAsignatura = new javax.swing.JMenu();
        itemAgregarAsignatura = new javax.swing.JMenuItem();
        itemBuscarAsignatura = new javax.swing.JMenuItem();
        itemEditarAsignatura = new javax.swing.JMenuItem();
        itemEliminarAsignatura = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesAsignatura = new javax.swing.JMenu();
        itemBuscarPorNombreAsignatura = new javax.swing.JMenuItem();
        itemBuscarPorIdAsignatura = new javax.swing.JMenuItem();
        menuClase = new javax.swing.JMenu();
        itemAgregarClase = new javax.swing.JMenuItem();
        itemBuscarClase = new javax.swing.JMenuItem();
        itemEditarClase = new javax.swing.JMenuItem();
        itemEliminarClase = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesClase = new javax.swing.JMenu();
        itemBuscarPorNombreClase = new javax.swing.JMenuItem();
        itemBuscarPorIdClase = new javax.swing.JMenuItem();
        menuSesion = new javax.swing.JMenu();
        itemAgregarSesion = new javax.swing.JMenuItem();
        itemBuscarSesion = new javax.swing.JMenuItem();
        itemEditarSesion = new javax.swing.JMenuItem();
        itemEliminarSesion = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesSesion = new javax.swing.JMenu();
        itemBuscarPorNombreSesion = new javax.swing.JMenuItem();
        itemBuscarPorIdSesion = new javax.swing.JMenuItem();
        menuBloqueHorario = new javax.swing.JMenu();
        itemAgregarBloqueHorario = new javax.swing.JMenuItem();
        itemBuscarBloqueHorario = new javax.swing.JMenuItem();
        itemEditarBloqueHorario = new javax.swing.JMenuItem();
        itemEliminarBloqueHorario = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesBloqueHorario = new javax.swing.JMenu();
        itemBuscarPorNombreBloqueHorario = new javax.swing.JMenuItem();
        itemBuscarPorIdBloqueHorario = new javax.swing.JMenuItem();
        menuAula = new javax.swing.JMenu();
        itemAgregarAula = new javax.swing.JMenuItem();
        itemBuscarAula = new javax.swing.JMenuItem();
        itemEditarAula = new javax.swing.JMenuItem();
        itemEliminarAula = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesAula = new javax.swing.JMenu();
        itemBuscarPorNombreAula = new javax.swing.JMenuItem();
        itemBuscarPorIdAula = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuNivelEducativo = new javax.swing.JMenu();
        itemAgregarNivelEducativo = new javax.swing.JMenuItem();
        itemBuscarNivelEducativo = new javax.swing.JMenuItem();
        itemEditarNivelEducativo = new javax.swing.JMenuItem();
        itemEliminarNivelEducativo = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesNivelEducativo = new javax.swing.JMenu();
        itemBuscarPorNombreNivelEducativo = new javax.swing.JMenuItem();
        itemBuscarPorIdNivelEducativo = new javax.swing.JMenuItem();
        menuModalidad = new javax.swing.JMenu();
        itemAgregarModalidad = new javax.swing.JMenuItem();
        itemBuscarModalidad = new javax.swing.JMenuItem();
        itemEditarModalidad = new javax.swing.JMenuItem();
        itemEliminarModalidad = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesModalidad = new javax.swing.JMenu();
        itemBuscarPorNombreModalidad = new javax.swing.JMenuItem();
        itemBuscarPorIdModalidad = new javax.swing.JMenuItem();
        menuCurso = new javax.swing.JMenu();
        itemAgregarCurso = new javax.swing.JMenuItem();
        itemBuscarCurso = new javax.swing.JMenuItem();
        itemEditarCurso = new javax.swing.JMenuItem();
        itemEliminarCurso = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesCurso = new javax.swing.JMenu();
        itemBuscarPorNombreCurso = new javax.swing.JMenuItem();
        itemBuscarPorIdCurso = new javax.swing.JMenuItem();
        menuGrupoInfantil = new javax.swing.JMenu();
        itemAgregarGrupoInfantil = new javax.swing.JMenuItem();
        itemBuscarGrupoInfantil = new javax.swing.JMenuItem();
        itemEditarGrupoInfantil = new javax.swing.JMenuItem();
        itemEliminarGrupoInfantil = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesGrupoInfantil = new javax.swing.JMenu();
        itemBuscarPorNombreGrupoInfantil = new javax.swing.JMenuItem();
        itemBuscarPorIdGrupoInfantil = new javax.swing.JMenuItem();
        menuGrupoRegular = new javax.swing.JMenu();
        itemAgregarGrupoRegular = new javax.swing.JMenuItem();
        itemBuscarGrupoRegular = new javax.swing.JMenuItem();
        itemEditarGrupoRegular = new javax.swing.JMenuItem();
        itemEliminarGrupoRegular = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesGrupoRegular = new javax.swing.JMenu();
        itemBuscarPorNombreGrupoRegular = new javax.swing.JMenuItem();
        itemBuscarPorIdGrupoRegular = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        categoriaUsuario.setText("Usuarios");

        menuAlumno.setText("Alumno");
        menuAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAlumnoMouseClicked(evt);
            }
        });

        itemAgregarAlumno.setText("Agregar...");
        itemAgregarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAgregarAlumnoMouseClicked(evt);
            }
        });
        itemAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAlumno(evt);
            }
        });
        menuAlumno.add(itemAgregarAlumno);

        itemBuscarAlumno.setText("Buscar...");
        itemBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAlumno(evt);
            }
        });
        menuAlumno.add(itemBuscarAlumno);

        itemEditarAlumno.setText("Modificar...");
        itemEditarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAlumno(evt);
            }
        });
        menuAlumno.add(itemEditarAlumno);

        itemEliminarAlumno.setText("Eliminar...");
        itemEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAlumno(evt);
            }
        });
        menuAlumno.add(itemEliminarAlumno);
        menuAlumno.add(jSeparator3);

        subMenuReportesAlumno.setText("Reportes");

        itemBuscarPorNombreAlumno.setText("Buscar por nombre");
        subMenuReportesAlumno.add(itemBuscarPorNombreAlumno);

        itemBuscarPorIdAlumno.setText("Buscar por id");
        subMenuReportesAlumno.add(itemBuscarPorIdAlumno);

        menuAlumno.add(subMenuReportesAlumno);

        categoriaUsuario.add(menuAlumno);

        menuAdministrativo.setText("Administrativo");

        itemAgregarAdministrativo.setText("Agregar...");
        itemAgregarAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAdministrativo(evt);
            }
        });
        menuAdministrativo.add(itemAgregarAdministrativo);

        itemBuscarAdministrativo.setText("Buscar...");
        itemBuscarAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAdministrativo(evt);
            }
        });
        menuAdministrativo.add(itemBuscarAdministrativo);

        itemEditarAdministrativo.setText("Modificar...");
        itemEditarAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAdministrativo(evt);
            }
        });
        menuAdministrativo.add(itemEditarAdministrativo);

        itemEliminarAdministrativo.setText("Eliminar...");
        itemEliminarAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAdministrativo(evt);
            }
        });
        menuAdministrativo.add(itemEliminarAdministrativo);
        menuAdministrativo.add(jSeparator4);

        subMenuReportesAdministrativo.setText("Reportes");

        itemBuscarPorNombreAdministrativo.setText("Buscar por nombre");
        subMenuReportesAdministrativo.add(itemBuscarPorNombreAdministrativo);

        itemBuscarPorIdAdministrativo.setText("Buscar por id");
        subMenuReportesAdministrativo.add(itemBuscarPorIdAdministrativo);

        menuAdministrativo.add(subMenuReportesAdministrativo);

        categoriaUsuario.add(menuAdministrativo);

        menuProfesorRegular.setText("Profesor Regular");

        itemAgregarProfesorRegular.setText("Agregar...");
        itemAgregarProfesorRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorRegular(evt);
            }
        });
        menuProfesorRegular.add(itemAgregarProfesorRegular);

        itemBuscarProfesorRegular.setText("Buscar...");
        itemBuscarProfesorRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorRegular(evt);
            }
        });
        menuProfesorRegular.add(itemBuscarProfesorRegular);

        itemEditarProfesorRegular.setText("Modificar...");
        itemEditarProfesorRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorRegular(evt);
            }
        });
        menuProfesorRegular.add(itemEditarProfesorRegular);

        itemEliminarProfesorRegular.setText("Eliminar...");
        itemEliminarProfesorRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorRegular(evt);
            }
        });
        menuProfesorRegular.add(itemEliminarProfesorRegular);
        menuProfesorRegular.add(jSeparator5);

        subMenuReportesProfesorRegular.setText("Reportes");

        itemBuscarPorNombreProfesorRegular.setText("Buscar por nombre");
        subMenuReportesProfesorRegular.add(itemBuscarPorNombreProfesorRegular);

        itemBuscarPorIdProfesorRegular.setText("Buscar por id");
        subMenuReportesProfesorRegular.add(itemBuscarPorIdProfesorRegular);

        menuProfesorRegular.add(subMenuReportesProfesorRegular);

        categoriaUsuario.add(menuProfesorRegular);

        menuProfesorInfantil.setText("Profesor Infantil");

        itemAgregarProfesorInfantil.setText("Agregar...");
        itemAgregarProfesorInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorInfantil(evt);
            }
        });
        menuProfesorInfantil.add(itemAgregarProfesorInfantil);

        itemBuscarProfesorInfantil.setText("Buscar...");
        itemBuscarProfesorInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorInfantil(evt);
            }
        });
        menuProfesorInfantil.add(itemBuscarProfesorInfantil);

        itemEditarProfesorInfantil.setText("Modificar...");
        itemEditarProfesorInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorInfantil(evt);
            }
        });
        menuProfesorInfantil.add(itemEditarProfesorInfantil);

        itemEliminarProfesorInfantil.setText("Eliminar...");
        itemEliminarProfesorInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioProfesorInfantil(evt);
            }
        });
        menuProfesorInfantil.add(itemEliminarProfesorInfantil);
        menuProfesorInfantil.add(jSeparator6);

        subMenuReportesProfesorInfantil.setText("Reportes");

        itemBuscarPorNombreProfesorInfantil.setText("Buscar por nombre");
        subMenuReportesProfesorInfantil.add(itemBuscarPorNombreProfesorInfantil);

        itemBuscarPorIdProfesorInfantil.setText("Buscar por id");
        subMenuReportesProfesorInfantil.add(itemBuscarPorIdProfesorInfantil);

        menuProfesorInfantil.add(subMenuReportesProfesorInfantil);

        categoriaUsuario.add(menuProfesorInfantil);

        itemLoginUsuario.setText("Iniciar sesion");
        itemLoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginUsuarioActionPerformed(evt);
            }
        });
        categoriaUsuario.add(itemLoginUsuario);

        itemRecordarClaveUsuario.setText("Recordar password");
        itemRecordarClaveUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecordarClaveUsuarioActionPerformed(evt);
            }
        });
        categoriaUsuario.add(itemRecordarClaveUsuario);

        itemCambiarClaveUsuario.setText("Cambiar password");
        categoriaUsuario.add(itemCambiarClaveUsuario);

        itemSalirUsuario.setText("Salir");
        categoriaUsuario.add(itemSalirUsuario);

        jMenuBar1.add(categoriaUsuario);

        categoriaVinculacion.setText("Vinculación");

        menuMatricula.setText("Matricula");

        itemAgregarMatricula.setText("Agregar...");
        menuMatricula.add(itemAgregarMatricula);

        itemBuscarMatricula.setText("Buscar...");
        menuMatricula.add(itemBuscarMatricula);

        itemEditarMatricula.setText("Modificar...");
        menuMatricula.add(itemEditarMatricula);

        itemEliminarMatricula.setText("Eliminar...");
        menuMatricula.add(itemEliminarMatricula);
        menuMatricula.add(jSeparator7);

        subMenuReportesMatricula.setText("Reportes");

        itemBuscarPorEstudianteMatricula.setText("Buscar por nombre");
        subMenuReportesMatricula.add(itemBuscarPorEstudianteMatricula);

        itemBuscarPorIdMatricula.setText("Buscar por id");
        subMenuReportesMatricula.add(itemBuscarPorIdMatricula);

        menuMatricula.add(subMenuReportesMatricula);

        categoriaVinculacion.add(menuMatricula);

        menuBeca.setText("Beca");

        itemAgregarBeca.setText("Agregar...");
        menuBeca.add(itemAgregarBeca);

        itemBuscarBeca.setText("Buscar...");
        menuBeca.add(itemBuscarBeca);

        itemEditarBeca.setText("Modificar...");
        menuBeca.add(itemEditarBeca);

        itemEliminarBeca.setText("Eliminar...");
        menuBeca.add(itemEliminarBeca);
        menuBeca.add(jSeparator8);

        subMenuReportesBeca.setText("Reportes");

        itemBuscarPorNombreBeca.setText("Buscar por nombre");
        subMenuReportesBeca.add(itemBuscarPorNombreBeca);

        itemBuscarPorIdBeca.setText("Buscar por id");
        subMenuReportesBeca.add(itemBuscarPorIdBeca);

        menuBeca.add(subMenuReportesBeca);

        categoriaVinculacion.add(menuBeca);
        categoriaVinculacion.add(jSeparator2);

        menuContrato.setText("Contrato");

        itemAgregarContrato.setText("Agregar...");
        menuContrato.add(itemAgregarContrato);

        itemBuscarContrato.setText("Buscar...");
        menuContrato.add(itemBuscarContrato);

        itemEditarContrato.setText("Modificar...");
        menuContrato.add(itemEditarContrato);

        itemEliminarContrato.setText("Eliminar...");
        menuContrato.add(itemEliminarContrato);
        menuContrato.add(jSeparator9);

        subMenuReportesContrato.setText("Reportes");

        itemBuscarPorNombreContrato.setText("Buscar por nombre");
        subMenuReportesContrato.add(itemBuscarPorNombreContrato);

        itemBuscarPorIdContrato.setText("Buscar por id");
        subMenuReportesContrato.add(itemBuscarPorIdContrato);

        menuContrato.add(subMenuReportesContrato);

        categoriaVinculacion.add(menuContrato);

        jMenuBar1.add(categoriaVinculacion);

        categoriaAdministracion.setText("Administración");

        menuCicloAcademico.setText("Ciclo Academico");

        itemAgregarCicloAcademico.setText("Agregar...");
        itemAgregarCicloAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCicloAcademico(evt);
            }
        });
        menuCicloAcademico.add(itemAgregarCicloAcademico);

        itemBuscarCicloAcademico.setText("Buscar...");
        itemBuscarCicloAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCicloAcademico(evt);
            }
        });
        menuCicloAcademico.add(itemBuscarCicloAcademico);

        itemEditarCicloAcademico.setText("Modificar...");
        itemEditarCicloAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCicloAcademico(evt);
            }
        });
        menuCicloAcademico.add(itemEditarCicloAcademico);

        itemEliminarCicloAcademico.setText("Eliminar...");
        itemEliminarCicloAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCicloAcademico(evt);
            }
        });
        menuCicloAcademico.add(itemEliminarCicloAcademico);
        menuCicloAcademico.add(jSeparator10);

        subMenuReportesCicloAcademico.setText("Reportes");

        itemBuscarPorAnioCicloAcademico.setText("Buscar por nombre");
        subMenuReportesCicloAcademico.add(itemBuscarPorAnioCicloAcademico);

        itemBuscarPorIdCicloAcademico.setText("Buscar por id");
        subMenuReportesCicloAcademico.add(itemBuscarPorIdCicloAcademico);

        menuCicloAcademico.add(subMenuReportesCicloAcademico);

        categoriaAdministracion.add(menuCicloAcademico);

        menuServicioComplementario.setText("Servicio Complementario");

        itemAgregarServicioComplementario.setText("Agregar...");
        menuServicioComplementario.add(itemAgregarServicioComplementario);

        itemBuscarServicioComplementario.setText("Buscar...");
        menuServicioComplementario.add(itemBuscarServicioComplementario);

        itemEditarServicioComplementario.setText("Modificar...");
        menuServicioComplementario.add(itemEditarServicioComplementario);

        itemEliminarServicioComplementario.setText("Eliminar...");
        menuServicioComplementario.add(itemEliminarServicioComplementario);
        menuServicioComplementario.add(jSeparator11);

        subMenuReportesServicioComplementario.setText("Reportes");

        itemBuscarPorNombreServicioComplementario.setText("Buscar por nombre");
        subMenuReportesServicioComplementario.add(itemBuscarPorNombreServicioComplementario);

        itemBuscarPorIdServicioComplementario.setText("Buscar por id");
        subMenuReportesServicioComplementario.add(itemBuscarPorIdServicioComplementario);

        menuServicioComplementario.add(subMenuReportesServicioComplementario);

        categoriaAdministracion.add(menuServicioComplementario);

        jMenuBar1.add(categoriaAdministracion);

        categoriaOrganizacion.setText("Organización");

        menuAsignatura.setText("Asignatura");

        itemAgregarAsignatura.setText("Agregar...");
        itemAgregarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAsignatura(evt);
            }
        });
        menuAsignatura.add(itemAgregarAsignatura);

        itemBuscarAsignatura.setText("Buscar...");
        itemBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAsignatura(evt);
            }
        });
        menuAsignatura.add(itemBuscarAsignatura);

        itemEditarAsignatura.setText("Modificar...");
        itemEditarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAsignatura(evt);
            }
        });
        menuAsignatura.add(itemEditarAsignatura);

        itemEliminarAsignatura.setText("Eliminar...");
        itemEliminarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAsignatura(evt);
            }
        });
        menuAsignatura.add(itemEliminarAsignatura);
        menuAsignatura.add(jSeparator12);

        subMenuReportesAsignatura.setText("Reportes");

        itemBuscarPorNombreAsignatura.setText("Buscar por nombre");
        subMenuReportesAsignatura.add(itemBuscarPorNombreAsignatura);

        itemBuscarPorIdAsignatura.setText("Buscar por id");
        subMenuReportesAsignatura.add(itemBuscarPorIdAsignatura);

        menuAsignatura.add(subMenuReportesAsignatura);

        categoriaOrganizacion.add(menuAsignatura);

        menuClase.setText("Clase");

        itemAgregarClase.setText("Agregar...");
        menuClase.add(itemAgregarClase);

        itemBuscarClase.setText("Buscar...");
        menuClase.add(itemBuscarClase);

        itemEditarClase.setText("Modificar...");
        menuClase.add(itemEditarClase);

        itemEliminarClase.setText("Eliminar...");
        menuClase.add(itemEliminarClase);
        menuClase.add(jSeparator13);

        subMenuReportesClase.setText("Reportes");

        itemBuscarPorNombreClase.setText("Buscar por nombre");
        subMenuReportesClase.add(itemBuscarPorNombreClase);

        itemBuscarPorIdClase.setText("Buscar por id");
        subMenuReportesClase.add(itemBuscarPorIdClase);

        menuClase.add(subMenuReportesClase);

        categoriaOrganizacion.add(menuClase);

        menuSesion.setText("Sesion");

        itemAgregarSesion.setText("Agregar...");
        menuSesion.add(itemAgregarSesion);

        itemBuscarSesion.setText("Buscar...");
        menuSesion.add(itemBuscarSesion);

        itemEditarSesion.setText("Modificar...");
        menuSesion.add(itemEditarSesion);

        itemEliminarSesion.setText("Eliminar...");
        menuSesion.add(itemEliminarSesion);
        menuSesion.add(jSeparator14);

        subMenuReportesSesion.setText("Reportes");

        itemBuscarPorNombreSesion.setText("Buscar por nombre");
        subMenuReportesSesion.add(itemBuscarPorNombreSesion);

        itemBuscarPorIdSesion.setText("Buscar por id");
        subMenuReportesSesion.add(itemBuscarPorIdSesion);

        menuSesion.add(subMenuReportesSesion);

        categoriaOrganizacion.add(menuSesion);

        menuBloqueHorario.setText("Bloque Horario");

        itemAgregarBloqueHorario.setText("Agregar...");
        menuBloqueHorario.add(itemAgregarBloqueHorario);

        itemBuscarBloqueHorario.setText("Buscar...");
        menuBloqueHorario.add(itemBuscarBloqueHorario);

        itemEditarBloqueHorario.setText("Modificar...");
        menuBloqueHorario.add(itemEditarBloqueHorario);

        itemEliminarBloqueHorario.setText("Eliminar...");
        menuBloqueHorario.add(itemEliminarBloqueHorario);
        menuBloqueHorario.add(jSeparator15);

        subMenuReportesBloqueHorario.setText("Reportes");

        itemBuscarPorNombreBloqueHorario.setText("Buscar por nombre");
        subMenuReportesBloqueHorario.add(itemBuscarPorNombreBloqueHorario);

        itemBuscarPorIdBloqueHorario.setText("Buscar por id");
        subMenuReportesBloqueHorario.add(itemBuscarPorIdBloqueHorario);

        menuBloqueHorario.add(subMenuReportesBloqueHorario);

        categoriaOrganizacion.add(menuBloqueHorario);

        menuAula.setText("Aula");

        itemAgregarAula.setText("Agregar...");
        itemAgregarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAula(evt);
            }
        });
        menuAula.add(itemAgregarAula);

        itemBuscarAula.setText("Buscar...");
        itemBuscarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAula(evt);
            }
        });
        menuAula.add(itemBuscarAula);

        itemEditarAula.setText("Modificar...");
        itemEditarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAula(evt);
            }
        });
        menuAula.add(itemEditarAula);

        itemEliminarAula.setText("Eliminar...");
        itemEliminarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAula(evt);
            }
        });
        menuAula.add(itemEliminarAula);
        menuAula.add(jSeparator16);

        subMenuReportesAula.setText("Reportes");

        itemBuscarPorNombreAula.setText("Buscar por nombre");
        subMenuReportesAula.add(itemBuscarPorNombreAula);

        itemBuscarPorIdAula.setText("Buscar por id");
        subMenuReportesAula.add(itemBuscarPorIdAula);

        menuAula.add(subMenuReportesAula);

        categoriaOrganizacion.add(menuAula);
        categoriaOrganizacion.add(jSeparator1);

        menuNivelEducativo.setText("Nivel Educativo");

        itemAgregarNivelEducativo.setText("Agregar...");
        itemAgregarNivelEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioNivelEducativo(evt);
            }
        });
        menuNivelEducativo.add(itemAgregarNivelEducativo);

        itemBuscarNivelEducativo.setText("Buscar...");
        itemBuscarNivelEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioNivelEducativo(evt);
            }
        });
        menuNivelEducativo.add(itemBuscarNivelEducativo);

        itemEditarNivelEducativo.setText("Modificar...");
        itemEditarNivelEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioNivelEducativo(evt);
            }
        });
        menuNivelEducativo.add(itemEditarNivelEducativo);

        itemEliminarNivelEducativo.setText("Eliminar...");
        itemEliminarNivelEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioNivelEducativo(evt);
            }
        });
        menuNivelEducativo.add(itemEliminarNivelEducativo);
        menuNivelEducativo.add(jSeparator17);

        subMenuReportesNivelEducativo.setText("Reportes");

        itemBuscarPorNombreNivelEducativo.setText("Buscar por nombre");
        subMenuReportesNivelEducativo.add(itemBuscarPorNombreNivelEducativo);

        itemBuscarPorIdNivelEducativo.setText("Buscar por id");
        subMenuReportesNivelEducativo.add(itemBuscarPorIdNivelEducativo);

        menuNivelEducativo.add(subMenuReportesNivelEducativo);

        categoriaOrganizacion.add(menuNivelEducativo);

        menuModalidad.setText("Modalidad");

        itemAgregarModalidad.setText("Agregar...");
        itemAgregarModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioModalidad(evt);
            }
        });
        menuModalidad.add(itemAgregarModalidad);

        itemBuscarModalidad.setText("Buscar...");
        menuModalidad.add(itemBuscarModalidad);

        itemEditarModalidad.setText("Modificar...");
        menuModalidad.add(itemEditarModalidad);

        itemEliminarModalidad.setText("Eliminar...");
        menuModalidad.add(itemEliminarModalidad);
        menuModalidad.add(jSeparator18);

        subMenuReportesModalidad.setText("Reportes");

        itemBuscarPorNombreModalidad.setText("Buscar por nombre");
        subMenuReportesModalidad.add(itemBuscarPorNombreModalidad);

        itemBuscarPorIdModalidad.setText("Buscar por id");
        subMenuReportesModalidad.add(itemBuscarPorIdModalidad);

        menuModalidad.add(subMenuReportesModalidad);

        categoriaOrganizacion.add(menuModalidad);

        menuCurso.setText("Curso");

        itemAgregarCurso.setText("Agregar...");
        itemAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCurso(evt);
            }
        });
        menuCurso.add(itemAgregarCurso);

        itemBuscarCurso.setText("Buscar...");
        itemBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCurso(evt);
            }
        });
        menuCurso.add(itemBuscarCurso);

        itemEditarCurso.setText("Modificar...");
        itemEditarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCurso(evt);
            }
        });
        menuCurso.add(itemEditarCurso);

        itemEliminarCurso.setText("Eliminar...");
        itemEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioCurso(evt);
            }
        });
        menuCurso.add(itemEliminarCurso);
        menuCurso.add(jSeparator19);

        subMenuReportesCurso.setText("Reportes");

        itemBuscarPorNombreCurso.setText("Buscar por nombre");
        subMenuReportesCurso.add(itemBuscarPorNombreCurso);

        itemBuscarPorIdCurso.setText("Buscar por id");
        subMenuReportesCurso.add(itemBuscarPorIdCurso);

        menuCurso.add(subMenuReportesCurso);

        categoriaOrganizacion.add(menuCurso);

        menuGrupoInfantil.setText("Grupo Infantil");

        itemAgregarGrupoInfantil.setText("Agregar...");
        menuGrupoInfantil.add(itemAgregarGrupoInfantil);

        itemBuscarGrupoInfantil.setText("Buscar...");
        menuGrupoInfantil.add(itemBuscarGrupoInfantil);

        itemEditarGrupoInfantil.setText("Modificar...");
        menuGrupoInfantil.add(itemEditarGrupoInfantil);

        itemEliminarGrupoInfantil.setText("Eliminar...");
        menuGrupoInfantil.add(itemEliminarGrupoInfantil);
        menuGrupoInfantil.add(jSeparator20);

        subMenuReportesGrupoInfantil.setText("Reportes");

        itemBuscarPorNombreGrupoInfantil.setText("Buscar por nombre");
        subMenuReportesGrupoInfantil.add(itemBuscarPorNombreGrupoInfantil);

        itemBuscarPorIdGrupoInfantil.setText("Buscar por id");
        subMenuReportesGrupoInfantil.add(itemBuscarPorIdGrupoInfantil);

        menuGrupoInfantil.add(subMenuReportesGrupoInfantil);

        categoriaOrganizacion.add(menuGrupoInfantil);

        menuGrupoRegular.setText("Grupo Regular");

        itemAgregarGrupoRegular.setText("Agregar...");
        menuGrupoRegular.add(itemAgregarGrupoRegular);

        itemBuscarGrupoRegular.setText("Buscar...");
        menuGrupoRegular.add(itemBuscarGrupoRegular);

        itemEditarGrupoRegular.setText("Modificar...");
        menuGrupoRegular.add(itemEditarGrupoRegular);

        itemEliminarGrupoRegular.setText("Eliminar...");
        menuGrupoRegular.add(itemEliminarGrupoRegular);
        menuGrupoRegular.add(jSeparator21);

        subMenuReportesGrupoRegular.setText("Reportes");

        itemBuscarPorNombreGrupoRegular.setText("Buscar por nombre");
        subMenuReportesGrupoRegular.add(itemBuscarPorNombreGrupoRegular);

        itemBuscarPorIdGrupoRegular.setText("Buscar por id");
        subMenuReportesGrupoRegular.add(itemBuscarPorIdGrupoRegular);

        menuGrupoRegular.add(subMenuReportesGrupoRegular);

        categoriaOrganizacion.add(menuGrupoRegular);

        jMenuBar1.add(categoriaOrganizacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemLoginUsuarioActionPerformed

    private void itemRecordarClaveUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecordarClaveUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRecordarClaveUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void menuAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAlumnoMouseClicked

    private void itemAgregarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAgregarAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgregarAlumnoMouseClicked

    private void FormularioAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioAlumno
        // TODO add your handling code here:
        AlumnoFormulario ventana = new AlumnoFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioAlumno

    private void FormularioAsignatura(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioAsignatura
        // TODO add your handling code here:
        AsignaturaFormulario ventana = new AsignaturaFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioAsignatura

    private void FormularioCicloAcademico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioCicloAcademico
        // TODO add your handling code here:
        CicloAcademicoFormulario ventana = new CicloAcademicoFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioCicloAcademico

    private void FormularioNivelEducativo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioNivelEducativo
        // TODO add your handling code here:
        NivelEducativoFormulario ventana = new NivelEducativoFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioNivelEducativo

    private void FormularioModalidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioModalidad
        // TODO add your handling code here:
        ModalidadFormulario ventana = new ModalidadFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioModalidad

    private void FormularioProfesorInfantil(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioProfesorInfantil
        // TODO add your handling code here:
        ProfesorInfantilFormulario ventana = new ProfesorInfantilFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioProfesorInfantil

    private void FormularioProfesorRegular(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioProfesorRegular
        // TODO add your handling code here:
        ProfesorRegularFormulario ventana = new ProfesorRegularFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioProfesorRegular

    private void FormularioAdministrativo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioAdministrativo
        // TODO add your handling code here:
        AdministrativoFormulario ventana = new AdministrativoFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioAdministrativo

    private void FormularioAula(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioAula
        // TODO add your handling code here:
        AulaFormulario ventana = new AulaFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioAula

    private void FormularioCurso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioCurso
        // TODO add your handling code here:
        CursoFormulario ventana = new CursoFormulario(this, false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_FormularioCurso

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu categoriaAdministracion;
    private javax.swing.JMenu categoriaOrganizacion;
    private javax.swing.JMenu categoriaUsuario;
    private javax.swing.JMenu categoriaVinculacion;
    private javax.swing.JMenuItem itemAgregarAdministrativo;
    private javax.swing.JMenuItem itemAgregarAlumno;
    private javax.swing.JMenuItem itemAgregarAsignatura;
    private javax.swing.JMenuItem itemAgregarAula;
    private javax.swing.JMenuItem itemAgregarBeca;
    private javax.swing.JMenuItem itemAgregarBloqueHorario;
    private javax.swing.JMenuItem itemAgregarCicloAcademico;
    private javax.swing.JMenuItem itemAgregarClase;
    private javax.swing.JMenuItem itemAgregarContrato;
    private javax.swing.JMenuItem itemAgregarCurso;
    private javax.swing.JMenuItem itemAgregarGrupoInfantil;
    private javax.swing.JMenuItem itemAgregarGrupoRegular;
    private javax.swing.JMenuItem itemAgregarMatricula;
    private javax.swing.JMenuItem itemAgregarModalidad;
    private javax.swing.JMenuItem itemAgregarNivelEducativo;
    private javax.swing.JMenuItem itemAgregarProfesorInfantil;
    private javax.swing.JMenuItem itemAgregarProfesorRegular;
    private javax.swing.JMenuItem itemAgregarServicioComplementario;
    private javax.swing.JMenuItem itemAgregarSesion;
    private javax.swing.JMenuItem itemBuscarAdministrativo;
    private javax.swing.JMenuItem itemBuscarAlumno;
    private javax.swing.JMenuItem itemBuscarAsignatura;
    private javax.swing.JMenuItem itemBuscarAula;
    private javax.swing.JMenuItem itemBuscarBeca;
    private javax.swing.JMenuItem itemBuscarBloqueHorario;
    private javax.swing.JMenuItem itemBuscarCicloAcademico;
    private javax.swing.JMenuItem itemBuscarClase;
    private javax.swing.JMenuItem itemBuscarContrato;
    private javax.swing.JMenuItem itemBuscarCurso;
    private javax.swing.JMenuItem itemBuscarGrupoInfantil;
    private javax.swing.JMenuItem itemBuscarGrupoRegular;
    private javax.swing.JMenuItem itemBuscarMatricula;
    private javax.swing.JMenuItem itemBuscarModalidad;
    private javax.swing.JMenuItem itemBuscarNivelEducativo;
    private javax.swing.JMenuItem itemBuscarPorAnioCicloAcademico;
    private javax.swing.JMenuItem itemBuscarPorEstudianteMatricula;
    private javax.swing.JMenuItem itemBuscarPorIdAdministrativo;
    private javax.swing.JMenuItem itemBuscarPorIdAlumno;
    private javax.swing.JMenuItem itemBuscarPorIdAsignatura;
    private javax.swing.JMenuItem itemBuscarPorIdAula;
    private javax.swing.JMenuItem itemBuscarPorIdBeca;
    private javax.swing.JMenuItem itemBuscarPorIdBloqueHorario;
    private javax.swing.JMenuItem itemBuscarPorIdCicloAcademico;
    private javax.swing.JMenuItem itemBuscarPorIdClase;
    private javax.swing.JMenuItem itemBuscarPorIdContrato;
    private javax.swing.JMenuItem itemBuscarPorIdCurso;
    private javax.swing.JMenuItem itemBuscarPorIdGrupoInfantil;
    private javax.swing.JMenuItem itemBuscarPorIdGrupoRegular;
    private javax.swing.JMenuItem itemBuscarPorIdMatricula;
    private javax.swing.JMenuItem itemBuscarPorIdModalidad;
    private javax.swing.JMenuItem itemBuscarPorIdNivelEducativo;
    private javax.swing.JMenuItem itemBuscarPorIdProfesorInfantil;
    private javax.swing.JMenuItem itemBuscarPorIdProfesorRegular;
    private javax.swing.JMenuItem itemBuscarPorIdServicioComplementario;
    private javax.swing.JMenuItem itemBuscarPorIdSesion;
    private javax.swing.JMenuItem itemBuscarPorNombreAdministrativo;
    private javax.swing.JMenuItem itemBuscarPorNombreAlumno;
    private javax.swing.JMenuItem itemBuscarPorNombreAsignatura;
    private javax.swing.JMenuItem itemBuscarPorNombreAula;
    private javax.swing.JMenuItem itemBuscarPorNombreBeca;
    private javax.swing.JMenuItem itemBuscarPorNombreBloqueHorario;
    private javax.swing.JMenuItem itemBuscarPorNombreClase;
    private javax.swing.JMenuItem itemBuscarPorNombreContrato;
    private javax.swing.JMenuItem itemBuscarPorNombreCurso;
    private javax.swing.JMenuItem itemBuscarPorNombreGrupoInfantil;
    private javax.swing.JMenuItem itemBuscarPorNombreGrupoRegular;
    private javax.swing.JMenuItem itemBuscarPorNombreModalidad;
    private javax.swing.JMenuItem itemBuscarPorNombreNivelEducativo;
    private javax.swing.JMenuItem itemBuscarPorNombreProfesorInfantil;
    private javax.swing.JMenuItem itemBuscarPorNombreProfesorRegular;
    private javax.swing.JMenuItem itemBuscarPorNombreServicioComplementario;
    private javax.swing.JMenuItem itemBuscarPorNombreSesion;
    private javax.swing.JMenuItem itemBuscarProfesorInfantil;
    private javax.swing.JMenuItem itemBuscarProfesorRegular;
    private javax.swing.JMenuItem itemBuscarServicioComplementario;
    private javax.swing.JMenuItem itemBuscarSesion;
    private javax.swing.JMenuItem itemCambiarClaveUsuario;
    private javax.swing.JMenuItem itemEditarAdministrativo;
    private javax.swing.JMenuItem itemEditarAlumno;
    private javax.swing.JMenuItem itemEditarAsignatura;
    private javax.swing.JMenuItem itemEditarAula;
    private javax.swing.JMenuItem itemEditarBeca;
    private javax.swing.JMenuItem itemEditarBloqueHorario;
    private javax.swing.JMenuItem itemEditarCicloAcademico;
    private javax.swing.JMenuItem itemEditarClase;
    private javax.swing.JMenuItem itemEditarContrato;
    private javax.swing.JMenuItem itemEditarCurso;
    private javax.swing.JMenuItem itemEditarGrupoInfantil;
    private javax.swing.JMenuItem itemEditarGrupoRegular;
    private javax.swing.JMenuItem itemEditarMatricula;
    private javax.swing.JMenuItem itemEditarModalidad;
    private javax.swing.JMenuItem itemEditarNivelEducativo;
    private javax.swing.JMenuItem itemEditarProfesorInfantil;
    private javax.swing.JMenuItem itemEditarProfesorRegular;
    private javax.swing.JMenuItem itemEditarServicioComplementario;
    private javax.swing.JMenuItem itemEditarSesion;
    private javax.swing.JMenuItem itemEliminarAdministrativo;
    private javax.swing.JMenuItem itemEliminarAlumno;
    private javax.swing.JMenuItem itemEliminarAsignatura;
    private javax.swing.JMenuItem itemEliminarAula;
    private javax.swing.JMenuItem itemEliminarBeca;
    private javax.swing.JMenuItem itemEliminarBloqueHorario;
    private javax.swing.JMenuItem itemEliminarCicloAcademico;
    private javax.swing.JMenuItem itemEliminarClase;
    private javax.swing.JMenuItem itemEliminarContrato;
    private javax.swing.JMenuItem itemEliminarCurso;
    private javax.swing.JMenuItem itemEliminarGrupoInfantil;
    private javax.swing.JMenuItem itemEliminarGrupoRegular;
    private javax.swing.JMenuItem itemEliminarMatricula;
    private javax.swing.JMenuItem itemEliminarModalidad;
    private javax.swing.JMenuItem itemEliminarNivelEducativo;
    private javax.swing.JMenuItem itemEliminarProfesorInfantil;
    private javax.swing.JMenuItem itemEliminarProfesorRegular;
    private javax.swing.JMenuItem itemEliminarServicioComplementario;
    private javax.swing.JMenuItem itemEliminarSesion;
    private javax.swing.JMenuItem itemLoginUsuario;
    private javax.swing.JMenuItem itemRecordarClaveUsuario;
    private javax.swing.JMenuItem itemSalirUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu menuAdministrativo;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenu menuAsignatura;
    private javax.swing.JMenu menuAula;
    private javax.swing.JMenu menuBeca;
    private javax.swing.JMenu menuBloqueHorario;
    private javax.swing.JMenu menuCicloAcademico;
    private javax.swing.JMenu menuClase;
    private javax.swing.JMenu menuContrato;
    private javax.swing.JMenu menuCurso;
    private javax.swing.JMenu menuGrupoInfantil;
    private javax.swing.JMenu menuGrupoRegular;
    private javax.swing.JMenu menuMatricula;
    private javax.swing.JMenu menuModalidad;
    private javax.swing.JMenu menuNivelEducativo;
    private javax.swing.JMenu menuProfesorInfantil;
    private javax.swing.JMenu menuProfesorRegular;
    private javax.swing.JMenu menuServicioComplementario;
    private javax.swing.JMenu menuSesion;
    private javax.swing.JMenu subMenuReportesAdministrativo;
    private javax.swing.JMenu subMenuReportesAlumno;
    private javax.swing.JMenu subMenuReportesAsignatura;
    private javax.swing.JMenu subMenuReportesAula;
    private javax.swing.JMenu subMenuReportesBeca;
    private javax.swing.JMenu subMenuReportesBloqueHorario;
    private javax.swing.JMenu subMenuReportesCicloAcademico;
    private javax.swing.JMenu subMenuReportesClase;
    private javax.swing.JMenu subMenuReportesContrato;
    private javax.swing.JMenu subMenuReportesCurso;
    private javax.swing.JMenu subMenuReportesGrupoInfantil;
    private javax.swing.JMenu subMenuReportesGrupoRegular;
    private javax.swing.JMenu subMenuReportesMatricula;
    private javax.swing.JMenu subMenuReportesModalidad;
    private javax.swing.JMenu subMenuReportesNivelEducativo;
    private javax.swing.JMenu subMenuReportesProfesorInfantil;
    private javax.swing.JMenu subMenuReportesProfesorRegular;
    private javax.swing.JMenu subMenuReportesServicioComplementario;
    private javax.swing.JMenu subMenuReportesSesion;
    // End of variables declaration//GEN-END:variables
}
